# Generated by Django 6.0.1 on 2026-02-08 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='برند خودرو')),
            ],
        ),
        migrations.CreateModel(
            name='DamageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='شماره مرحله')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مرحله')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'مرحله دریافت خسارت',
                'verbose_name_plural': 'مراحل دریافت خسارت',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویژگی')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('icon_class', models.CharField(max_length=100, verbose_name='کد آیکون FontAwesome')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('insurance_type', models.CharField(default='مشاوره کلی', max_length=100, verbose_name='نوع مشاوره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بیمه')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نشانی (Slug)')),
                ('image', models.ImageField(upload_to='insurance_icons/', verbose_name='آیکون/تصویر')),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن نشان (مثلاً: تخفیف ویژه)')),
                ('category', models.CharField(choices=[('insurance', 'بیمه'), ('service', 'کالا و خدمات'), ('investment', 'سرمایه\u200cگذاری')], default='insurance', max_length=20, verbose_name='دسته بندی')),
                ('insurance_type', models.CharField(choices=[('third_party', 'شخص ثالث'), ('body', 'بدنه'), ('none', 'سایر (بدون نرخ محاسباتی)')], default='none', max_length=20, verbose_name='نوع پوشش (برای محاسبات)')),
                ('price_start', models.CharField(blank=True, max_length=100, null=True, verbose_name='شروع قیمت از')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
            ],
            options={
                'verbose_name': 'کارت بیمه',
                'verbose_name_plural': 'کارت\u200cهای بیمه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('logo', models.ImageField(upload_to='companies/', verbose_name='لوگو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('wealth_level', models.IntegerField(default=1, verbose_name='سطح توانگری')),
                ('complaint_response_rate', models.IntegerField(default=100, verbose_name='درصد پاسخگویی به شکایات')),
            ],
            options={
                'verbose_name': 'شرکت بیمه همکار',
                'verbose_name_plural': 'شرکت\u200cهای بیمه همکار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بیمه')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('image', models.ImageField(upload_to='insurance_info/', verbose_name='تصویر')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='لینک صفحه بیشتر')),
            ],
            options={
                'verbose_name': 'اطلاعات بیمه',
                'verbose_name_plural': 'اطلاعات بیمه',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('icon_class', models.CharField(default='fa-circle', max_length=50, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته بندی منو',
                'verbose_name_plural': 'دسته بندی\u200cهای منو',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مرحله')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='trust/', verbose_name='تصویر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'گام اعتماد',
                'verbose_name_plural': 'گام\u200cهای اعتماد',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('wallet_balance', models.PositiveIntegerField(default=0, verbose_name='موجودی کیف پول')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'همه کاربران (سایت و ادمین)',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='مدل خودرو')),
                ('base_price', models.BigIntegerField(default=0, verbose_name='قیمت پایه بازار (تومان)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مزیت (مثلاً: امنیت مالی)')),
                ('description', models.TextField(verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(upload_to='benefits/', verbose_name='آیکون گرافیکی (SVG یا PNG)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('insurance_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.insurancecard', verbose_name='مربوط به بیمه')),
            ],
            options={
                'verbose_name': 'مزیت بیمه',
                'verbose_name_plural': 'مزایای بیمه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('third_party', 'بیمه شخص ثالث'), ('car_body', 'بیمه بدنه')], max_length=20, verbose_name='نوع بیمه')),
                ('address', models.TextField(verbose_name='آدرس بازدید')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insurancecompany', verbose_name='شرکت بیمه')),
            ],
            options={
                'verbose_name': 'گزارش خسارت',
                'verbose_name_plural': 'گزارش\u200cهای خسارت',
            },
        ),
        migrations.CreateModel(
            name='InsuranceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('body', 'بدنه'), ('third_party', 'ثالث')], max_length=20, verbose_name='نوع بیمه')),
                ('base_fee', models.BigIntegerField(verbose_name='حق بیمه پایه (ریال)')),
                ('car_value_coefficient', models.FloatField(default=0.005, verbose_name='ضریب ارزش خودرو')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.insurancecompany', verbose_name='شرکت بیمه')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('external_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک خارجی (در صورت عدم انتخاب بیمه)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menucategory')),
                ('insurance_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.insurancecard', verbose_name='اتصال به صفحه بیمه')),
            ],
            options={
                'verbose_name': 'آیتم زیرمنو',
                'verbose_name_plural': 'آیتم\u200cهای زیرمنو',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ ثبت شده')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدی'), ('installment', 'اقساطی')], default='cash', max_length=20, verbose_name='نوع پرداخت')),
                ('installments_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد اقساط')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت بیمه')),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره پلاک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت کلی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=10)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_orders', to='core.insurancecard', verbose_name='بیمه')),
                ('insurance_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.insurancecompany', verbose_name='شرکت بیمه همکار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفرش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت قسط')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت واقعی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
            },
        ),
    ]
