# Generated by Django 6.0.1 on 2026-02-08 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'مدل خودرو', 'verbose_name_plural': 'مدل\u200cهای خودرو'},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'بنزینی'), ('diesel', 'دیزلی'), ('hybrid', 'هیبرید'), ('electric', 'برقی'), ('cng', 'دوگانه سوز')], default='gasoline', max_length=20, verbose_name='نوع سوخت'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='base_price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت پایه (ریال/تومان)'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.carbrand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مدل'),
        ),
    ]
