# Generated by Django 6.0.1 on 2026-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carmodel_options_carmodel_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True, verbose_name='نشانی (Slug)'),
        ),
        migrations.AddField(
            model_name='insuranceinfo',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True, verbose_name='نشانی (Slug)'),
        ),
        migrations.AlterField(
            model_name='insuranceinfo',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='لینک خارجی (در صورت خالی بودن از اسلاگ استفاده می\u200cشود)'),
        ),
    ]
