# Generated by Django 6.0.1 on 2026-02-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_slug_insurance_info_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecard',
            name='insurance_group',
            field=models.CharField(choices=[('persons', 'بیمه اشخاص'), ('property', 'بیمه اموال'), ('liability', 'بیمه مسئولیت'), ('vehicle', 'بیمه وسایل نقلیه'), ('other', 'سایر')], default='other', max_length=20, verbose_name='گروه بیمه (اشخاص/اموال/مسئولیت/وسایل نقلیه)'),
        ),
    ]
