# Generated by Django 6.0.1 on 2026-02-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_insurance_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecard',
            name='insurance_group',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات صفحه'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True, verbose_name='نشانی صفحه (Slug)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='external_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک خارجی (فقط وقتی اسلاگ و بیمه خالی باشد)'),
        ),
    ]
