# Generated by Django 6.0.1 on 2026-02-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_insurance_group_add_menuitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='برند موتور')),
            ],
            options={
                'verbose_name': 'برند موتور',
                'verbose_name_plural': 'برندهای موتور',
            },
        ),
        migrations.CreateModel(
            name='ProductionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='سال ساخت (مثلاً ۱۴۰۳)')),
            ],
            options={
                'verbose_name': 'سال ساخت',
                'verbose_name_plural': 'سال\u200cهای ساخت',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='MotorcycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('base_price', models.BigIntegerField(default=0, verbose_name='قیمت پایه (ریال)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.motorcyclebrand', verbose_name='برند موتور')),
            ],
            options={
                'verbose_name': 'مدل موتور',
                'verbose_name_plural': 'مدل\u200cهای موتور',
            },
        ),
    ]
