# Generated by Django 6.0.1 on 2026-02-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_motorcycle_brand_model_production_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionYear',
        ),
    ]
